### ISSUE TITLE
double/duplicate TCP messages ?

### ISSUE THREAD

**Issue by LeaseOnLife** [dgiardini/rtl-ais#23]
I seem to be getting every message twice, via TCP to OpenCPN:

output of rtl-ais with "./rtl_ais -T -P 11111 -n -R on" :
`!AIVDM,1,1,,A,H4eIMs@L4hDpD00000000000000,0*68
`
output of OpenCPN/nmea debug window:
`08:25:46 (TCP:127.0.0.1:11111) !AIVDM,1,1,,A,H4eIMs@L4hDpD00000000000000,0*68<0x0D><0x0A>
08:25:56 (TCP:127.0.0.1:11111) !AIVDM,1,1,,A,H4eIMs@L4hDpD00000000000000,0*68<0x0D><0x0A>
`
this seems specific to rtl-ais, when using a PI4 as TCP server with an old NMEA0183 AIS connected via serial port, I am not getting duplicate messages.

**Comment by dgiardini** [comment]
rtl-ais as used as tcp listener (-T switch)  kepps arriving messages in memory for 15 secs by default. The client, ie OpenCPN , gets all the AIS data available from rtl-ais so can pick many times the same message until is deleted. 
In most cases  getting twice the same message is not a problem, but  you can change this behaviour, using  -t parameter in order to lower the time the messages are stored in rtl-ais memory.
