### ISSUE TITLE
install: cannot stat 'rtl_ais': No such file or directory #103

### ISSUE THREAD

**Issue by galacticfr** [dgiardini/rtl-ais#46]
could you tell me where I can get that file? I tried running rtl_ais.c and rtl_ais.h but none of them worked

**Comment by dgiardini** [comment]
Hi

  rtl_ais.c and rtl_ais.h are source files,  you need the executable file
in order to work.
 Please tell us which OS you are using so we can give you some guides.

Regards, David

**Comment by dgiardini** [comment]
On windows seems to be ok, use the "-n"  switch so you can see any incoming
sentences.

On Linux, may be the port is in use,  you can try using another one (" -P
10120 " for example). Use "-n" too.

Don't forget to set the ppm correctly to match the dongle error, you won't
see any incoming data otherwise

**Comment by galacticfr** [comment]
![Screenshot from 2024-04-04 10-21-53](https://github.com/dgiardini/rtl-ais/assets/103539723/455e76bf-47d4-4916-a240-da66e12c7934)
I still have the same issue on linux. I tried different ports but none of them worked

**Comment by dgiardini** [comment]
Your problem is not the ports, is the ppm, you are not specifying anyone,
and that mostly doesn't work.

Look at the README file on github, at known issues:
https://github.com/dgiardini/rtl-ais?tab=readme-ov-file#known-issues
There are some guidelines there.

You can also google "rtr-sdr calibration"; you'll find a lot Of results,
look for something easy for you.

As a result of the calibration, you'll get a number, that is the error of
your RTL-SDR device in parts per million (aka ppm). You must pass this
number
 as a parameter to  the program using  "-p <your_ppm>". The ppm is specific
to the dongle, so you can use it on Linux, Windows, even other computers,
always with the same dongle.

Good luck !
David
